//
//  ColorDefinitions.swift
//  WristSteps WatchKit Extension
//
//  Created by Michael Schoder on 04.02.21.
//

import SwiftUI

extension AppColor {
    static let all: [AppColor] = Self.standard + Self.premium
    static let standard: [AppColor] = [appBlue, appCyan, appGreen, appOrange, appPurple, appRed]
    static let premium: [AppColor] = [prem1, prem2, prem3, prem4, prem5, prem6, prem7, prem8, prem9, prem10, prem11, prem12, prem13, prem14, prem15, prem16, prem17, prem18, prem19, prem20, prem21, prem22, prem23, prem24, prem25, prem26, prem27, prem28, prem29, prem30, prem31, prem32, prem33, prem34, prem35, prem36, prem37, prem38, prem39, prem40, prem41, prem42, prem43, prem44, prem45, prem46, prem47, prem48, prem49, prem50, prem51, prem52, prem53, prem54, prem55, prem56, prem57, prem58, prem59, prem60, prem61, prem62, prem63, prem64, prem65, prem66, prem67, prem68, prem69, prem70, prem71, prem72, prem73, prem74, prem75, prem76, prem77, prem78, prem79, prem80, prem81]

    static let appBlue = AppColor(name: "appBlue", localizationKey: "color.appBlue", color: Color("appBlue"))
    static let appCyan = AppColor(name: "appCyan", localizationKey: "color.appCyan", color: Color("appCyan"))
    static let appGreen = AppColor(name: "appGreen", localizationKey: "color.appGreen", color: Color("appGreen"))
    static let appOrange = AppColor(name: "appOrange", localizationKey: "color.appOrange", color: Color("appOrange"))
    static let appPurple = AppColor(name: "appPurple", localizationKey: "color.appPurple", color: Color("appPurple"))
    static let appRed = AppColor(name: "appRed", localizationKey: "color.appRed", color: Color("appRed"))

    static let prem1 = AppColor(name: "prem1", localizationKey: "color.prem1", color: Color("prem1"))
    static let prem2 = AppColor(name: "prem2", localizationKey: "color.prem2", color: Color("prem2"))
    static let prem3 = AppColor(name: "prem3", localizationKey: "color.prem3", color: Color("prem3"))
    static let prem4 = AppColor(name: "prem4", localizationKey: "color.prem4", color: Color("prem4"))
    static let prem5 = AppColor(name: "prem5", localizationKey: "color.prem5", color: Color("prem5"))
    static let prem6 = AppColor(name: "prem6", localizationKey: "color.prem6", color: Color("prem6"))
    static let prem7 = AppColor(name: "prem7", localizationKey: "color.prem7", color: Color("prem7"))
    static let prem8 = AppColor(name: "prem8", localizationKey: "color.prem8", color: Color("prem8"))
    static let prem9 = AppColor(name: "prem9", localizationKey: "color.prem9", color: Color("prem9"))
    static let prem10 = AppColor(name: "prem10", localizationKey: "color.prem10", color: Color("prem10"))
    static let prem11 = AppColor(name: "prem11", localizationKey: "color.prem11", color: Color("prem11"))
    static let prem12 = AppColor(name: "prem12", localizationKey: "color.prem12", color: Color("prem12"))
    static let prem13 = AppColor(name: "prem13", localizationKey: "color.prem13", color: Color("prem13"))
    static let prem14 = AppColor(name: "prem14", localizationKey: "color.prem14", color: Color("prem14"))
    static let prem15 = AppColor(name: "prem15", localizationKey: "color.prem15", color: Color("prem15"))
    static let prem16 = AppColor(name: "prem16", localizationKey: "Flash Light6", color: Color("prem16"))
    static let prem17 = AppColor(name: "prem17", localizationKey: "color.prem17", color: Color("prem17"))
    static let prem18 = AppColor(name: "prem18", localizationKey: "color.prem18", color: Color("prem18"))
    static let prem19 = AppColor(name: "prem19", localizationKey: "color.prem19", color: Color("prem19"))
    static let prem20 = AppColor(name: "prem20", localizationKey: "color.prem20", color: Color("prem20"))
    static let prem21 = AppColor(name: "prem21", localizationKey: "color.prem21", color: Color("prem21"))
    static let prem22 = AppColor(name: "prem22", localizationKey: "color.prem22", color: Color("prem22"))
    static let prem23 = AppColor(name: "prem23", localizationKey: "color.prem23", color: Color("prem23"))
    static let prem24 = AppColor(name: "prem24", localizationKey: "color.prem24", color: Color("prem24"))
    static let prem25 = AppColor(name: "prem25", localizationKey: "color.prem25", color: Color("prem25"))
    static let prem26 = AppColor(name: "prem26", localizationKey: "color.prem26", color: Color("prem26"))
    static let prem27 = AppColor(name: "prem27", localizationKey: "color.prem27", color: Color("prem27"))
    static let prem28 = AppColor(name: "prem28", localizationKey: "color.prem28", color: Color("prem28"))
    static let prem29 = AppColor(name: "prem29", localizationKey: "color.prem29", color: Color("prem29"))
    static let prem30 = AppColor(name: "prem30", localizationKey: "color.prem30", color: Color("prem30"))
    static let prem31 = AppColor(name: "prem31", localizationKey: "color.prem31", color: Color("prem31"))
    static let prem32 = AppColor(name: "prem32", localizationKey: "color.prem32", color: Color("prem32"))
    static let prem33 = AppColor(name: "prem33", localizationKey: "color.prem33", color: Color("prem33"))
    static let prem34 = AppColor(name: "prem34", localizationKey: "color.prem34", color: Color("prem34"))
    static let prem35 = AppColor(name: "prem35", localizationKey: "color.prem35", color: Color("prem35"))
    static let prem36 = AppColor(name: "prem36", localizationKey: "color.prem36", color: Color("prem36"))
    static let prem37 = AppColor(name: "prem37", localizationKey: "color.prem37", color: Color("prem37"))
    static let prem38 = AppColor(name: "prem38", localizationKey: "color.prem38", color: Color("prem38"))
    static let prem39 = AppColor(name: "prem39", localizationKey: "color.prem38", color: Color("prem39"))
    static let prem40 = AppColor(name: "prem40", localizationKey: "color.prem39", color: Color("prem40"))
    static let prem41 = AppColor(name: "prem41", localizationKey: "color.prem40", color: Color("prem41"))
    static let prem42 = AppColor(name: "prem42", localizationKey: "color.prem41", color: Color("prem42"))
    static let prem43 = AppColor(name: "prem43", localizationKey: "color.prem42", color: Color("prem43"))
    static let prem44 = AppColor(name: "prem44", localizationKey: "color.prem43", color: Color("prem44"))
    static let prem45 = AppColor(name: "prem45", localizationKey: "color.prem44", color: Color("prem45"))
    static let prem46 = AppColor(name: "prem46", localizationKey: "color.prem45", color: Color("prem46"))
    static let prem47 = AppColor(name: "prem47", localizationKey: "color.prem46", color: Color("prem47"))
    static let prem48 = AppColor(name: "prem48", localizationKey: "color.prem47", color: Color("prem48"))
    static let prem49 = AppColor(name: "prem49", localizationKey: "color.prem48", color: Color("prem49"))
    static let prem50 = AppColor(name: "prem50", localizationKey: "color.prem49", color: Color("prem50"))
    static let prem51 = AppColor(name: "prem51", localizationKey: "color.prem50", color: Color("prem51"))
    static let prem52 = AppColor(name: "prem52", localizationKey: "color.prem51", color: Color("prem52"))
    static let prem53 = AppColor(name: "prem53", localizationKey: "color.prem52", color: Color("prem53"))
    static let prem54 = AppColor(name: "prem54", localizationKey: "color.prem53", color: Color("prem54"))
    static let prem55 = AppColor(name: "prem55", localizationKey: "color.prem54", color: Color("prem55"))
    static let prem56 = AppColor(name: "prem56", localizationKey: "color.prem55", color: Color("prem56"))
    static let prem57 = AppColor(name: "prem57", localizationKey: "color.prem56", color: Color("prem57"))
    static let prem58 = AppColor(name: "prem58", localizationKey: "color.prem57", color: Color("prem58"))
    static let prem59 = AppColor(name: "prem59", localizationKey: "color.prem58", color: Color("prem59"))
    static let prem60 = AppColor(name: "prem60", localizationKey: "color.prem60", color: Color("prem60"))
    static let prem61 = AppColor(name: "prem61", localizationKey: "color.prem61", color: Color("prem61"))
    static let prem62 = AppColor(name: "prem62", localizationKey: "color.prem62", color: Color("prem62"))
    static let prem63 = AppColor(name: "prem63", localizationKey: "color.prem63", color: Color("prem63"))
    static let prem64 = AppColor(name: "prem64", localizationKey: "color.prem64", color: Color("prem64"))
    static let prem65 = AppColor(name: "prem65", localizationKey: "color.prem65", color: Color("prem65"))
    static let prem66 = AppColor(name: "prem66", localizationKey: "color.prem66", color: Color("prem66"))
    static let prem67 = AppColor(name: "prem67", localizationKey: "color.prem67", color: Color("prem67"))
    static let prem68 = AppColor(name: "prem68", localizationKey: "color.prem68", color: Color("prem68"))
    static let prem69 = AppColor(name: "prem69", localizationKey: "color.prem69", color: Color("prem69"))
    static let prem70 = AppColor(name: "prem70", localizationKey: "color.prem70", color: Color("prem70"))
    static let prem71 = AppColor(name: "prem71", localizationKey: "color.prem71", color: Color("prem71"))
    static let prem72 = AppColor(name: "prem72", localizationKey: "color.prem72", color: Color("prem72"))
    static let prem73 = AppColor(name: "prem73", localizationKey: "color.prem73", color: Color("prem73"))
    static let prem74 = AppColor(name: "prem74", localizationKey: "color.prem74", color: Color("prem74"))
    static let prem75 = AppColor(name: "prem75", localizationKey: "color.prem75", color: Color("prem75"))
    static let prem76 = AppColor(name: "prem76", localizationKey: "color.prem76", color: Color("prem76"))
    static let prem77 = AppColor(name: "prem77", localizationKey: "color.prem77", color: Color("prem77"))
    static let prem78 = AppColor(name: "prem78", localizationKey: "color.prem78", color: Color("prem78"))
    static let prem79 = AppColor(name: "prem79", localizationKey: "color.prem79", color: Color("prem79"))
    static let prem80 = AppColor(name: "prem80", localizationKey: "color.prem80", color: Color("prem80"))
    static let prem81 = AppColor(name: "prem81", localizationKey: "color.prem81", color: Color("prem81"))

}
