//
//  ColorDefinitions.swift
//  WristSteps WatchKit Extension
//
//  Created by Michael Schoder on 04.02.21.
//

import SwiftUI

extension AppColor {
    static let all: [AppColor] = Self.standard + Self.premium
    static let standard: [AppColor] = [appBlue, appCyan, appGreen, appOrange, appPurple, appRed]
    static let premium: [AppColor] = [prem1, prem2, prem3, prem4, prem5, prem6, prem7, prem8, prem9, prem10, prem11, prem12, prem13, prem14, prem15, prem16, prem17, prem18, prem19, prem20, prem21, prem22, prem23, prem24, prem25, prem26, prem27, prem28, prem29, prem30, prem31, prem32, prem33, prem34, prem35, prem36, prem37, prem38, prem39, prem40, prem41, prem42, prem43, prem44, prem45, prem46, prem47, prem48, prem49, prem50, prem51, prem52, prem53, prem54, prem55, prem56, prem57, prem58, prem59, prem60, prem61, prem62, prem63, prem64, prem65, prem66, prem67, prem68, prem69, prem70, prem71, prem72, prem73, prem74, prem75, prem76, prem77, prem78, prem79, prem80, prem81]

    static let appBlue = AppColor(name: "appBlue", displayName: "App Blue", color: Color("appBlue"))
    static let appCyan = AppColor(name: "appCyan", displayName: "App Cyan", color: Color("appCyan"))
    static let appGreen = AppColor(name: "appGreen", displayName: "App Green", color: Color("appGreen"))
    static let appOrange = AppColor(name: "appOrange", displayName: "App Orange", color: Color("appOrange"))
    static let appPurple = AppColor(name: "appPurple", displayName: "App Purple", color: Color("appPurple"))
    static let appRed = AppColor(name: "appRed", displayName: "App Red", color: Color("appRed"))

    static let prem1 = AppColor(name: "prem1", displayName: "Volt", color: Color("prem1"))
    static let prem2 = AppColor(name: "prem2", displayName: "White", color: Color("prem2"))
    static let prem3 = AppColor(name: "prem3", displayName: "Red", color: Color("prem3"))
    static let prem4 = AppColor(name: "prem4", displayName: "Orange", color: Color("prem4"))
    static let prem5 = AppColor(name: "prem5", displayName: "Clementine", color: Color("prem5"))
    static let prem6 = AppColor(name: "prem6", displayName: "Apricot", color: Color("prem6"))
    static let prem7 = AppColor(name: "prem7", displayName: "Peach", color: Color("prem7"))
    static let prem8 = AppColor(name: "prem8", displayName: "Papaya", color: Color("prem8"))
    static let prem9 = AppColor(name: "prem9", displayName: "Kumquat", color: Color("prem9"))
    static let prem10 = AppColor(name: "prem10", displayName: "Light Orange", color: Color("prem10"))
    static let prem11 = AppColor(name: "prem11", displayName: "Mellow Yellow", color: Color("prem11"))
    static let prem12 = AppColor(name: "prem12", displayName: "Lemon Cream", color: Color("prem12"))
    static let prem13 = AppColor(name: "prem13", displayName: "Yellow", color: Color("prem13"))
    static let prem14 = AppColor(name: "prem14", displayName: "Pollen", color: Color("prem14"))
    static let prem15 = AppColor(name: "prem15", displayName: "Canary Yellow", color: Color("prem15"))
    static let prem16 = AppColor(name: "prem16", displayName: "Flash Light", color: Color("prem16"))
    static let prem17 = AppColor(name: "prem17", displayName: "Flash", color: Color("prem17"))
    static let prem18 = AppColor(name: "prem18", displayName: "Green", color: Color("prem18"))
    static let prem19 = AppColor(name: "prem19", displayName: "Spearmint", color: Color("prem19"))
    static let prem20 = AppColor(name: "prem20", displayName: "Mint", color: Color("prem20"))
    static let prem21 = AppColor(name: "prem21", displayName: "Beryl", color: Color("prem21"))
    static let prem22 = AppColor(name: "prem22", displayName: "Sea Foam", color: Color("prem22"))
    static let prem23 = AppColor(name: "prem23", displayName: "Turquoise", color: Color("prem23"))
    static let prem24 = AppColor(name: "prem24", displayName: "Light Blue", color: Color("prem24"))
    static let prem25 = AppColor(name: "prem25", displayName: "Surf Blue", color: Color("prem25"))
    static let prem26 = AppColor(name: "prem26", displayName: "Blue", color: Color("prem26"))
    static let prem27 = AppColor(name: "prem27", displayName: "Royal Blue", color: Color("prem27"))
    static let prem28 = AppColor(name: "prem28", displayName: "Cerulean", color: Color("prem28"))
    static let prem29 = AppColor(name: "prem29", displayName: "Lilac", color: Color("prem29"))
    static let prem30 = AppColor(name: "prem30", displayName: "Mist Blue", color: Color("prem30"))
    static let prem31 = AppColor(name: "prem31", displayName: "Azure", color: Color("prem31"))
    static let prem32 = AppColor(name: "prem32", displayName: "Nothern Blue", color: Color("prem32"))
    static let prem33 = AppColor(name: "prem33", displayName: "Storm Grey", color: Color("prem33"))
    static let prem34 = AppColor(name: "prem34", displayName: "Cactus", color: Color("prem34"))
    static let prem35 = AppColor(name: "prem35", displayName: "Pacific Green", color: Color("prem35"))
    static let prem36 = AppColor(name: "prem36", displayName: "Blue Cobalt", color: Color("prem36"))
    static let prem37 = AppColor(name: "prem37", displayName: "Alaskan Blue", color: Color("prem37"))
    static let prem38 = AppColor(name: "prem38", displayName: "Dark Teal", color: Color("prem38"))
    static let prem39 = AppColor(name: "prem39", displayName: "Blue Horizon", color: Color("prem39"))
    static let prem40 = AppColor(name: "prem40", displayName: "Deep Navy", color: Color("prem40"))
    static let prem41 = AppColor(name: "prem41", displayName: "Linen Blue", color: Color("prem41"))
    static let prem42 = AppColor(name: "prem42", displayName: "Denim Blue", color: Color("prem42"))
    static let prem43 = AppColor(name: "prem43", displayName: "Midnight Blue", color: Color("prem43"))
    static let prem44 = AppColor(name: "prem44", displayName: "Ocean Blue", color: Color("prem44"))
    static let prem45 = AppColor(name: "prem45", displayName: "Delft Blue", color: Color("prem45"))
    static let prem46 = AppColor(name: "prem46", displayName: "Indigo", color: Color("prem46"))
    static let prem47 = AppColor(name: "prem47", displayName: "Purple", color: Color("prem47"))
    static let prem48 = AppColor(name: "prem48", displayName: "Ultra Violet", color: Color("prem48"))
    static let prem49 = AppColor(name: "prem49", displayName: "Lavender Grey", color: Color("prem49"))
    static let prem50 = AppColor(name: "prem50", displayName: "Lavender", color: Color("prem50"))
    static let prem51 = AppColor(name: "prem51", displayName: "Pink Sand", color: Color("prem51"))
    static let prem52 = AppColor(name: "prem52", displayName: "Light Pink", color: Color("prem52"))
    static let prem53 = AppColor(name: "prem53", displayName: "Vintage Rose", color: Color("prem53"))
    static let prem54 = AppColor(name: "prem54", displayName: "Grapefruit", color: Color("prem54"))
    static let prem55 = AppColor(name: "prem55", displayName: "Pink", color: Color("prem55"))
    static let prem56 = AppColor(name: "prem56", displayName: "Electric Pink", color: Color("prem56"))
    static let prem57 = AppColor(name: "prem57", displayName: "Pink Citrus", color: Color("prem57"))
    static let prem58 = AppColor(name: "prem58", displayName: "Neon Pink", color: Color("prem58"))
    static let prem59 = AppColor(name: "prem59", displayName: "Dragon Fruit", color: Color("prem59"))
    static let prem60 = AppColor(name: "prem60", displayName: "Hibiscus", color: Color("prem60"))
    static let prem61 = AppColor(name: "prem61", displayName: "Pomegranate", color: Color("prem61"))
    static let prem62 = AppColor(name: "prem62", displayName: "Plum", color: Color("prem62"))
    static let prem63 = AppColor(name: "prem63", displayName: "Rose Red", color: Color("prem63"))
    static let prem64 = AppColor(name: "prem64", displayName: "Camellia", color: Color("prem64"))
    static let prem65 = AppColor(name: "prem65", displayName: "Flamingo", color: Color("prem65"))
    static let prem66 = AppColor(name: "prem66", displayName: "Camel", color: Color("prem66"))
    static let prem67 = AppColor(name: "prem67", displayName: "Walnut", color: Color("prem67"))
    static let prem68 = AppColor(name: "prem68", displayName: "Stone", color: Color("prem68"))
    static let prem69 = AppColor(name: "prem69", displayName: "Antique White", color: Color("prem69"))
    static let prem70 = AppColor(name: "prem70", displayName: "Cream", color: Color("prem70"))
    static let prem71 = AppColor(name: "prem71", displayName: "Soft White", color: Color("prem71"))
    static let prem72 = AppColor(name: "prem72", displayName: "Pebble", color: Color("prem72"))
    static let prem73 = AppColor(name: "prem73", displayName: "Cocoa", color: Color("prem73"))
    static let prem74 = AppColor(name: "prem74", displayName: "Coastal Grey", color: Color("prem74"))
    static let prem75 = AppColor(name: "prem75", displayName: "Dark Olive", color: Color("prem75"))
    static let prem76 = AppColor(name: "prem76", displayName: "Khaki", color: Color("prem76"))
    static let prem77 = AppColor(name: "prem77", displayName: "Pine Green", color: Color("prem77"))
    static let prem78 = AppColor(name: "prem78", displayName: "Cyprus Green", color: Color("prem78"))
    static let prem79 = AppColor(name: "prem79", displayName: "Gold", color: Color("prem79"))
    static let prem80 = AppColor(name: "prem80", displayName: "Rose Gold", color: Color("prem80"))
    static let prem81 = AppColor(name: "prem81", displayName: "Yellow Gold", color: Color("prem81"))

}
